/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.MouseAdapter;

/**
 *
 * @author GeGa
 */
public class V_eventUser extends javax.swing.JFrame {

    /**
     * Creates new form EventUser
     */
    int mouseX;
    int mouseY;
    public V_eventUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        foto1 = new javax.swing.JLabel();
        judul1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        judul2 = new javax.swing.JLabel();
        judul7 = new javax.swing.JLabel();
        foto2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        judul3 = new javax.swing.JLabel();
        foto3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        judul5 = new javax.swing.JLabel();
        foto5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        judul4 = new javax.swing.JLabel();
        foto4 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        judul6 = new javax.swing.JLabel();
        foto6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        homeBtn = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        eventBtn = new javax.swing.JLabel();
        pengaduanBtn = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        settingBtn = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel21.setBackground(new java.awt.Color(27, 27, 27));
        jPanel21.setMaximumSize(new java.awt.Dimension(1366, 768));
        jPanel21.setMinimumSize(new java.awt.Dimension(1366, 768));
        jPanel21.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel22.setBackground(new java.awt.Color(51, 51, 51));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(25, 25, 25));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        foto1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        foto1.setForeground(new java.awt.Color(255, 255, 255));
        foto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        foto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/berita.png"))); // NOI18N
        jPanel3.add(foto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        judul1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        judul1.setForeground(new java.awt.Color(255, 255, 255));
        judul1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul1.setText("LOREM IPSUM DOLOR SIT AMET");
        jPanel3.add(judul1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 210, 420, 80));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(153, 153, 153));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("30 September 2019");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 30));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 160, 30));

        jPanel22.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 423, 320));

        jPanel5.setBackground(new java.awt.Color(25, 25, 25));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(153, 153, 153));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("30 September 2019");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -1, 160, 30));

        jPanel5.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 160, 30));

        judul2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        judul2.setForeground(new java.awt.Color(255, 255, 255));
        judul2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul2.setText("LOREM IPSUM DOLOR SIT AMET");
        jPanel5.add(judul2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 210, 420, 80));

        judul7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        judul7.setForeground(new java.awt.Color(255, 255, 255));
        judul7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul7.setText("LOREM IPSUM DOLOR SIT AMET");
        jPanel5.add(judul7, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 210, 420, 80));

        foto2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        foto2.setForeground(new java.awt.Color(255, 255, 255));
        foto2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        foto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/berita.png"))); // NOI18N
        jPanel5.add(foto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel22.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 423, 320));

        jPanel6.setBackground(new java.awt.Color(25, 25, 25));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(51, 51, 51));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(153, 153, 153));
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("30 September 2019");
        jPanel10.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -1, 160, 30));

        jPanel6.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 160, 30));

        judul3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        judul3.setForeground(new java.awt.Color(255, 255, 255));
        judul3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul3.setText("LOREM IPSUM DOLOR SIT AMET");
        jPanel6.add(judul3, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 210, 420, 80));

        foto3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        foto3.setForeground(new java.awt.Color(255, 255, 255));
        foto3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        foto3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/berita.png"))); // NOI18N
        jPanel6.add(foto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel22.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, 423, 320));

        jPanel8.setBackground(new java.awt.Color(25, 25, 25));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBackground(new java.awt.Color(51, 51, 51));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setBackground(new java.awt.Color(153, 153, 153));
        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("30 September 2019");
        jPanel12.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -1, 160, 30));

        jPanel8.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 160, 30));

        judul5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        judul5.setForeground(new java.awt.Color(255, 255, 255));
        judul5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul5.setText("LOREM IPSUM DOLOR SIT AMET");
        jPanel8.add(judul5, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 210, 420, 80));

        foto5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        foto5.setForeground(new java.awt.Color(255, 255, 255));
        foto5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        foto5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/berita.png"))); // NOI18N
        jPanel8.add(foto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel22.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, 423, 320));

        jPanel7.setBackground(new java.awt.Color(25, 25, 25));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(51, 51, 51));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setBackground(new java.awt.Color(153, 153, 153));
        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("30 September 2019");
        jPanel11.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -1, 160, 30));

        jPanel7.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 160, 30));

        judul4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        judul4.setForeground(new java.awt.Color(255, 255, 255));
        judul4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul4.setText("LOREM IPSUM DOLOR SIT AMET");
        jPanel7.add(judul4, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 210, 420, 80));

        foto4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        foto4.setForeground(new java.awt.Color(255, 255, 255));
        foto4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        foto4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/berita.png"))); // NOI18N
        jPanel7.add(foto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel22.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 423, 320));

        jPanel9.setBackground(new java.awt.Color(25, 25, 25));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(51, 51, 51));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setBackground(new java.awt.Color(153, 153, 153));
        jLabel16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("30 September 2019");
        jPanel13.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -1, 160, 30));

        jPanel9.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 160, 30));

        judul6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        judul6.setForeground(new java.awt.Color(255, 255, 255));
        judul6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul6.setText("LOREM IPSUM DOLOR SIT AMET");
        jPanel9.add(judul6, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 210, 420, 80));

        foto6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        foto6.setForeground(new java.awt.Color(255, 255, 255));
        foto6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        foto6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/berita.png"))); // NOI18N
        jPanel9.add(foto6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel22.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 350, 423, 320));

        jPanel21.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 77, 1330, 680));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/head.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        jPanel21.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 280, 27));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Exit.png"))); // NOI18N
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel21.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 10, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Minimize.png"))); // NOI18N
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel21.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 10, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Maximize.png"))); // NOI18N
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel21.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(25, 25, 25));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homeBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        homeBtn.setForeground(new java.awt.Color(255, 255, 255));
        homeBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/BERANDA BLANK.png"))); // NOI18N
        homeBtn.setText(" BERANDA");
        jPanel1.add(homeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/BATAS.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 0, -1, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/BATAS.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, -1, 50));

        eventBtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        eventBtn.setForeground(new java.awt.Color(118, 185, 0));
        eventBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eventBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/EVENT FILL.png"))); // NOI18N
        eventBtn.setText(" EVENT");
        jPanel1.add(eventBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        pengaduanBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        pengaduanBtn.setForeground(new java.awt.Color(255, 255, 255));
        pengaduanBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pengaduanBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/pengaduan blank.png"))); // NOI18N
        pengaduanBtn.setText(" PENGADUAN");
        jPanel1.add(pengaduanBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/BATAS.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, -1, 50));

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/USER BLANK.png"))); // NOI18N
        jLabel9.setText(" GEOFANY GALINDRA");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 10, -1, -1));

        settingBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        settingBtn.setForeground(new java.awt.Color(255, 255, 255));
        settingBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        settingBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/SETTING BLANK.png"))); // NOI18N
        jPanel1.add(settingBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 10, -1, -1));

        logoutBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        logoutBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/EXIT BLANK.png"))); // NOI18N
        jPanel1.add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, -1, -1));

        jPanel21.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 1330, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void klikHome(MouseAdapter action){
        homeBtn.addMouseListener(action);
    }
    
    public void klikPengaduan(MouseAdapter action) {
        pengaduanBtn.addMouseListener(action);
    }
    
    public void klikLogout(MouseAdapter action){
        logoutBtn.addMouseListener(action);
    }
    
    public void klikSetting(MouseAdapter action) {
        settingBtn.addMouseListener(action);
    }
    
    public void klikDetail(MouseAdapter action){
        foto1.addMouseListener(action);
        foto2.addMouseListener(action);
        foto3.addMouseListener(action);
        foto4.addMouseListener(action);
        foto5.addMouseListener(action);
        foto6.addMouseListener(action);
        judul1.addMouseListener(action);
        judul2.addMouseListener(action);
        judul3.addMouseListener(action);
        judul4.addMouseListener(action);
        judul5.addMouseListener(action);
        judul6.addMouseListener(action);        
    }
    
    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        // TODO add your handling code here:
        int koordinatX = evt.getXOnScreen();
        int koordinatY = evt.getYOnScreen();
        this.setLocation(koordinatX-mouseX, koordinatY-mouseY);
    }//GEN-LAST:event_jLabel1MouseDragged

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        // TODO add your handling code here:
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        this.dispose();
        System.exit(1);
    }//GEN-LAST:event_jLabel11MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_eventUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_eventUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_eventUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_eventUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_eventUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel eventBtn;
    private javax.swing.JLabel foto1;
    private javax.swing.JLabel foto2;
    private javax.swing.JLabel foto3;
    private javax.swing.JLabel foto4;
    private javax.swing.JLabel foto5;
    private javax.swing.JLabel foto6;
    private javax.swing.JLabel homeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel judul1;
    private javax.swing.JLabel judul2;
    private javax.swing.JLabel judul3;
    private javax.swing.JLabel judul4;
    private javax.swing.JLabel judul5;
    private javax.swing.JLabel judul6;
    private javax.swing.JLabel judul7;
    private javax.swing.JLabel logoutBtn;
    private javax.swing.JLabel pengaduanBtn;
    private javax.swing.JLabel settingBtn;
    // End of variables declaration//GEN-END:variables
}
