/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.MouseAdapter;
import javax.swing.JOptionPane;

/**
 *
 * @author GeGa
 */
public class V_pengaduanAdmin extends javax.swing.JFrame {

    /**
     * Creates new form PengaduanAdmin
     */
    int mouseX;
    int mouseY;
    public V_pengaduanAdmin() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        tolakBtn3 = new javax.swing.JLabel();
        prosesBtn3 = new javax.swing.JLabel();
        selesaiBtn3 = new javax.swing.JLabel();
        status3 = new javax.swing.JLabel();
        jenis3 = new javax.swing.JLabel();
        judul3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        judul1 = new javax.swing.JLabel();
        jenis1 = new javax.swing.JLabel();
        prosesBtn1 = new javax.swing.JLabel();
        selesaiBtn1 = new javax.swing.JLabel();
        tolakBtn1 = new javax.swing.JLabel();
        status1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        tolakBtn2 = new javax.swing.JLabel();
        prosesBtn2 = new javax.swing.JLabel();
        selesaiBtn2 = new javax.swing.JLabel();
        status2 = new javax.swing.JLabel();
        jenis2 = new javax.swing.JLabel();
        judul2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        status5 = new javax.swing.JLabel();
        jenis5 = new javax.swing.JLabel();
        judul5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        status4 = new javax.swing.JLabel();
        jenis4 = new javax.swing.JLabel();
        judul4 = new javax.swing.JLabel();
        head = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        pengaduanBtn = new javax.swing.JLabel();
        eventBtn = new javax.swing.JLabel();
        homeBtn = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JLabel();
        exitBtn = new javax.swing.JLabel();
        minimizeBtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel21.setBackground(new java.awt.Color(27, 27, 27));
        jPanel21.setMaximumSize(new java.awt.Dimension(1366, 768));
        jPanel21.setMinimumSize(new java.awt.Dimension(1366, 768));
        jPanel21.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel22.setBackground(new java.awt.Color(51, 51, 51));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(26, 26, 26));
        jPanel5.setForeground(new java.awt.Color(26, 26, 26));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tolakBtn3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tolakBtn3.setForeground(new java.awt.Color(255, 255, 255));
        tolakBtn3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tolakBtn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/decline.png"))); // NOI18N
        jPanel5.add(tolakBtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 30, -1, -1));

        prosesBtn3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        prosesBtn3.setForeground(new java.awt.Color(255, 255, 255));
        prosesBtn3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prosesBtn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/wait not.png"))); // NOI18N
        jPanel5.add(prosesBtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 30, -1, -1));

        selesaiBtn3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        selesaiBtn3.setForeground(new java.awt.Color(255, 255, 255));
        selesaiBtn3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selesaiBtn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/aprrove.png"))); // NOI18N
        jPanel5.add(selesaiBtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 30, -1, -1));

        status3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        status3.setForeground(new java.awt.Color(255, 102, 0));
        status3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        status3.setText("Sedang Dalam Proses");
        jPanel5.add(status3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 30, 190, -1));

        jenis3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jenis3.setForeground(new java.awt.Color(153, 153, 153));
        jenis3.setText("Lorem Ipsum Dolor Sit Amet");
        jPanel5.add(jenis3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        judul3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        judul3.setForeground(new java.awt.Color(255, 255, 255));
        judul3.setText("Lorem Ipsum Dolor Sit Amet");
        jPanel5.add(judul3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel22.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 1310, 100));

        jPanel4.setBackground(new java.awt.Color(26, 26, 26));
        jPanel4.setForeground(new java.awt.Color(26, 26, 26));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        judul1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        judul1.setForeground(new java.awt.Color(255, 255, 255));
        judul1.setText("Lorem Ipsum Dolor Sit Amet");
        jPanel4.add(judul1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jenis1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jenis1.setForeground(new java.awt.Color(153, 153, 153));
        jenis1.setText("Lorem Ipsum Dolor Sit Amet");
        jPanel4.add(jenis1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        prosesBtn1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        prosesBtn1.setForeground(new java.awt.Color(255, 255, 255));
        prosesBtn1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prosesBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/wait.png"))); // NOI18N
        jPanel4.add(prosesBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 30, -1, -1));

        selesaiBtn1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        selesaiBtn1.setForeground(new java.awt.Color(255, 255, 255));
        selesaiBtn1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selesaiBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/aprrove not.png"))); // NOI18N
        jPanel4.add(selesaiBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 30, -1, -1));

        tolakBtn1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tolakBtn1.setForeground(new java.awt.Color(255, 255, 255));
        tolakBtn1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tolakBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/decline.png"))); // NOI18N
        jPanel4.add(tolakBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 30, -1, -1));

        status1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        status1.setForeground(new java.awt.Color(153, 153, 153));
        status1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        status1.setText("Menunggu Verifikasi");
        jPanel4.add(status1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 30, 170, -1));

        jPanel22.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 1310, 100));

        jPanel6.setBackground(new java.awt.Color(26, 26, 26));
        jPanel6.setForeground(new java.awt.Color(26, 26, 26));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tolakBtn2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tolakBtn2.setForeground(new java.awt.Color(255, 255, 255));
        tolakBtn2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tolakBtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/decline.png"))); // NOI18N
        jPanel6.add(tolakBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 30, -1, -1));

        prosesBtn2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        prosesBtn2.setForeground(new java.awt.Color(255, 255, 255));
        prosesBtn2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prosesBtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/wait.png"))); // NOI18N
        jPanel6.add(prosesBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 30, -1, -1));

        selesaiBtn2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        selesaiBtn2.setForeground(new java.awt.Color(255, 255, 255));
        selesaiBtn2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selesaiBtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/aprrove not.png"))); // NOI18N
        jPanel6.add(selesaiBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 30, -1, -1));

        status2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        status2.setForeground(new java.awt.Color(153, 153, 153));
        status2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        status2.setText("Menunggu Verifikasi");
        jPanel6.add(status2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 30, 170, -1));

        jenis2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jenis2.setForeground(new java.awt.Color(153, 153, 153));
        jenis2.setText("Lorem Ipsum Dolor Sit Amet");
        jPanel6.add(jenis2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        judul2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        judul2.setForeground(new java.awt.Color(255, 255, 255));
        judul2.setText("Lorem Ipsum Dolor Sit Amet");
        jPanel6.add(judul2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel22.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 1310, 100));

        jPanel7.setBackground(new java.awt.Color(26, 26, 26));
        jPanel7.setForeground(new java.awt.Color(26, 26, 26));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        status5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        status5.setForeground(new java.awt.Color(255, 0, 0));
        status5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        status5.setText("Ditolak");
        jPanel7.add(status5, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 30, 160, -1));

        jenis5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jenis5.setForeground(new java.awt.Color(153, 153, 153));
        jenis5.setText("Lorem Ipsum Dolor Sit Amet");
        jPanel7.add(jenis5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        judul5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        judul5.setForeground(new java.awt.Color(255, 255, 255));
        judul5.setText("Lorem Ipsum Dolor Sit Amet");
        jPanel7.add(judul5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel22.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 1310, 100));

        jPanel8.setBackground(new java.awt.Color(26, 26, 26));
        jPanel8.setForeground(new java.awt.Color(26, 26, 26));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        status4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        status4.setForeground(new java.awt.Color(118, 185, 0));
        status4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        status4.setText("Diterima");
        jPanel8.add(status4, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 30, 160, -1));

        jenis4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jenis4.setForeground(new java.awt.Color(153, 153, 153));
        jenis4.setText("Lorem Ipsum Dolor Sit Amet");
        jPanel8.add(jenis4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        judul4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        judul4.setForeground(new java.awt.Color(255, 255, 255));
        judul4.setText("Lorem Ipsum Dolor Sit Amet");
        jPanel8.add(judul4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel22.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 1310, 100));

        jPanel21.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 77, 1330, 680));

        head.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        head.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/head.png"))); // NOI18N
        head.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        head.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headMouseDragged(evt);
            }
        });
        head.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headMousePressed(evt);
            }
        });
        jPanel21.add(head, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 280, 27));

        jPanel1.setBackground(new java.awt.Color(25, 25, 25));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/BATAS.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 0, -1, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/BATAS.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, -1, 50));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/BATAS.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, -1, 50));

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/admin blank.png"))); // NOI18N
        jLabel14.setText(" ADMIN GEOFANY");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1087, 10, 190, -1));

        pengaduanBtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        pengaduanBtn.setForeground(new java.awt.Color(118, 185, 0));
        pengaduanBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pengaduanBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/PENGADUAN FILL.png"))); // NOI18N
        pengaduanBtn.setText(" PENGADUAN");
        jPanel1.add(pengaduanBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        eventBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        eventBtn.setForeground(new java.awt.Color(255, 255, 255));
        eventBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eventBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/EVENT BLANK.png"))); // NOI18N
        eventBtn.setText(" EVENT");
        jPanel1.add(eventBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        homeBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        homeBtn.setForeground(new java.awt.Color(255, 255, 255));
        homeBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/BERANDA BLANK.png"))); // NOI18N
        homeBtn.setText(" BERANDA");
        jPanel1.add(homeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        logoutBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        logoutBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/EXIT BLANK.png"))); // NOI18N
        logoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutBtnMouseClicked(evt);
            }
        });
        jPanel1.add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 10, -1, -1));

        jPanel21.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 1330, 50));

        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Exit.png"))); // NOI18N
        exitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnMouseClicked(evt);
            }
        });
        jPanel21.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 10, -1, -1));

        minimizeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Minimize.png"))); // NOI18N
        minimizeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimizeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeBtnMouseClicked(evt);
            }
        });
        jPanel21.add(minimizeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void klikEvent(MouseAdapter action){
        eventBtn.addMouseListener(action);
    }
    
    public void klikHome(MouseAdapter action) {
        homeBtn.addMouseListener(action);
    }
    
    public void klikLogout(MouseAdapter action){
        logoutBtn.addMouseListener(action);
    }
    
    public void klikDetail(MouseAdapter action){
        judul1.addMouseListener(action);
        judul2.addMouseListener(action);
        judul3.addMouseListener(action);
        judul4.addMouseListener(action);
        judul5.addMouseListener(action);
    }
    
    public void klikTolak(MouseAdapter action){
        tolakBtn1.addMouseListener(action);
        tolakBtn2.addMouseListener(action);
        tolakBtn3.addMouseListener(action);
    }
    
    public void klikProses(MouseAdapter action){
        prosesBtn1.addMouseListener(action);
        prosesBtn2.addMouseListener(action);
        prosesBtn3.addMouseListener(action);
    }
    
    public void klikSelesai(MouseAdapter action){
        selesaiBtn1.addMouseListener(action);
        selesaiBtn2.addMouseListener(action);
        selesaiBtn3.addMouseListener(action);
    }
    
    public void setPengaduan1(String Judul, String Jenis, String Status){
        judul1.setText(Judul);
        jenis1.setText(Jenis);
        status1.setText(Status);
    }
    
    public void setPengaduan2(String Judul, String Jenis, String Status){
        judul2.setText(Judul);
        jenis2.setText(Jenis);
        status2.setText(Status);
    }
    
    public void setPengaduan3(String Judul, String Jenis, String Status){
        judul3.setText(Judul);
        jenis3.setText(Jenis);
        status3.setText(Status);
    }
    
    public void setPengaduan4(String Judul, String Jenis, String Status){
        judul4.setText(Judul);
        jenis4.setText(Jenis);
        status4.setText(Status);
    }
    
    public void setPengaduan5(String Judul, String Jenis, String Status){
        judul5.setText(Judul);
        jenis5.setText(Jenis);
        status5.setText(Status);
    }
    
    public int confirm(String isi){
        return JOptionPane.showConfirmDialog(this, isi, "Confirm", JOptionPane.YES_NO_OPTION , JOptionPane.QUESTION_MESSAGE);
    }
    
    public void message(String isi){
        JOptionPane.showMessageDialog(this, isi);
    }
    
    private void headMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headMouseDragged
        // TODO add your handling code here:
        int koordinatX = evt.getXOnScreen();
        int koordinatY = evt.getYOnScreen();
        this.setLocation(koordinatX-mouseX, koordinatY-mouseY);
    }//GEN-LAST:event_headMouseDragged

    private void headMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headMousePressed
        // TODO add your handling code here:
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_headMousePressed

    private void logoutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseClicked
        // TODO add your handling code here:
        V_login logout = new V_login();
        logout.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutBtnMouseClicked

    private void exitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseClicked
        // TODO add your handling code here:
        this.dispose();
        System.exit(1);
    }//GEN-LAST:event_exitBtnMouseClicked

    private void minimizeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMouseClicked
        this.setState(V_login.ICONIFIED);    // TODO add your handling code here:
    }//GEN-LAST:event_minimizeBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_pengaduanAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_pengaduanAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_pengaduanAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_pengaduanAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_pengaduanAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel eventBtn;
    private javax.swing.JLabel exitBtn;
    private javax.swing.JLabel head;
    private javax.swing.JLabel homeBtn;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel jenis1;
    private javax.swing.JLabel jenis2;
    private javax.swing.JLabel jenis3;
    private javax.swing.JLabel jenis4;
    private javax.swing.JLabel jenis5;
    private javax.swing.JLabel judul1;
    private javax.swing.JLabel judul2;
    private javax.swing.JLabel judul3;
    private javax.swing.JLabel judul4;
    private javax.swing.JLabel judul5;
    private javax.swing.JLabel logoutBtn;
    private javax.swing.JLabel minimizeBtn;
    private javax.swing.JLabel pengaduanBtn;
    private javax.swing.JLabel prosesBtn1;
    private javax.swing.JLabel prosesBtn2;
    private javax.swing.JLabel prosesBtn3;
    private javax.swing.JLabel selesaiBtn1;
    private javax.swing.JLabel selesaiBtn2;
    private javax.swing.JLabel selesaiBtn3;
    private javax.swing.JLabel status1;
    private javax.swing.JLabel status2;
    private javax.swing.JLabel status3;
    private javax.swing.JLabel status4;
    private javax.swing.JLabel status5;
    private javax.swing.JLabel tolakBtn1;
    private javax.swing.JLabel tolakBtn2;
    private javax.swing.JLabel tolakBtn3;
    // End of variables declaration//GEN-END:variables
}
