/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.MouseAdapter;
import javax.swing.JOptionPane;

/**
 *
 * @author GeGa
 */
public class V_prosesPengaduan extends javax.swing.JFrame {

    /**
     * Creates new form ProsesPengaduan
     */
    int mouseX;
    int mouseY;
    public V_prosesPengaduan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel34 = new javax.swing.JLabel();
        pengaduanBaruBtn = new javax.swing.JLabel();
        prosesBtn = new javax.swing.JLabel();
        historyPengaduanBtn = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        judul1 = new javax.swing.JLabel();
        jenisPengaduan1 = new javax.swing.JLabel();
        status1 = new javax.swing.JLabel();
        hapusPengaduan1Btn = new javax.swing.JLabel();
        editPengaduan1Btn = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        status2 = new javax.swing.JLabel();
        hapusPengaduan2Btn = new javax.swing.JLabel();
        editPengaduan2Btn = new javax.swing.JLabel();
        judul2 = new javax.swing.JLabel();
        jenisPengaduan2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        status3 = new javax.swing.JLabel();
        judul3 = new javax.swing.JLabel();
        jenisPengaduan3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        status4 = new javax.swing.JLabel();
        judul4 = new javax.swing.JLabel();
        jenisPengaduan4 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        status5 = new javax.swing.JLabel();
        judul5 = new javax.swing.JLabel();
        jenisPengaduan5 = new javax.swing.JLabel();
        head = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        homeBtn = new javax.swing.JLabel();
        eventBtn = new javax.swing.JLabel();
        pengaduanBtn = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JLabel();
        settingBtn = new javax.swing.JLabel();
        exitBtn = new javax.swing.JLabel();
        minimizeBtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel21.setBackground(new java.awt.Color(27, 27, 27));
        jPanel21.setMaximumSize(new java.awt.Dimension(1366, 768));
        jPanel21.setMinimumSize(new java.awt.Dimension(1366, 768));
        jPanel21.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel22.setBackground(new java.awt.Color(51, 51, 51));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(25, 25, 25));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/BATAS.png"))); // NOI18N
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, -1, 50));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1330, 10));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/BATAS.png"))); // NOI18N
        jPanel2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, 50));

        pengaduanBaruBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        pengaduanBaruBtn.setForeground(new java.awt.Color(255, 255, 255));
        pengaduanBaruBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pengaduanBaruBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/tambah blank.png"))); // NOI18N
        pengaduanBaruBtn.setText(" BUAT PENGADUAN BARU");
        jPanel2.add(pengaduanBaruBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        prosesBtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        prosesBtn.setForeground(new java.awt.Color(118, 185, 0));
        prosesBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prosesBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/verifikasi fill.png"))); // NOI18N
        prosesBtn.setText(" DALAM PROSES");
        jPanel2.add(prosesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        historyPengaduanBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        historyPengaduanBtn.setForeground(new java.awt.Color(255, 255, 255));
        historyPengaduanBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        historyPengaduanBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/history blank.png"))); // NOI18N
        historyPengaduanBtn.setText(" HISTORY PENGADUAN");
        jPanel2.add(historyPengaduanBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, -1, -1));

        jPanel22.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1330, -1));

        jPanel4.setBackground(new java.awt.Color(26, 26, 26));
        jPanel4.setForeground(new java.awt.Color(26, 26, 26));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        judul1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        judul1.setForeground(new java.awt.Color(255, 255, 255));
        judul1.setText("Lorem Ipsum Dolor Sit Amet");
        jPanel4.add(judul1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jenisPengaduan1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jenisPengaduan1.setForeground(new java.awt.Color(153, 153, 153));
        jenisPengaduan1.setText("Lorem Ipsum Dolor Sit Amet");
        jPanel4.add(jenisPengaduan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        status1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        status1.setForeground(new java.awt.Color(153, 153, 153));
        status1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        status1.setText("Menunggu Verifikasi");
        jPanel4.add(status1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 30, 170, -1));

        hapusPengaduan1Btn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        hapusPengaduan1Btn.setForeground(new java.awt.Color(255, 255, 255));
        hapusPengaduan1Btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hapusPengaduan1Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/trash fill.png"))); // NOI18N
        jPanel4.add(hapusPengaduan1Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 30, -1, -1));

        editPengaduan1Btn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        editPengaduan1Btn.setForeground(new java.awt.Color(255, 255, 255));
        editPengaduan1Btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editPengaduan1Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/edit fill.png"))); // NOI18N
        jPanel4.add(editPengaduan1Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 30, -1, -1));

        jPanel22.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 1310, 100));

        jPanel6.setBackground(new java.awt.Color(26, 26, 26));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        status2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        status2.setForeground(new java.awt.Color(153, 153, 153));
        status2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        status2.setText("Menunggu Verifikasi");
        jPanel6.add(status2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 30, 170, -1));

        hapusPengaduan2Btn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        hapusPengaduan2Btn.setForeground(new java.awt.Color(255, 255, 255));
        hapusPengaduan2Btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hapusPengaduan2Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/trash fill.png"))); // NOI18N
        jPanel6.add(hapusPengaduan2Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 30, -1, -1));

        editPengaduan2Btn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        editPengaduan2Btn.setForeground(new java.awt.Color(255, 255, 255));
        editPengaduan2Btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editPengaduan2Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/edit fill.png"))); // NOI18N
        jPanel6.add(editPengaduan2Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 30, -1, -1));

        judul2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        judul2.setForeground(new java.awt.Color(255, 255, 255));
        judul2.setText("Lorem Ipsum Dolor Sit Amet");
        jPanel6.add(judul2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jenisPengaduan2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jenisPengaduan2.setForeground(new java.awt.Color(153, 153, 153));
        jenisPengaduan2.setText("Lorem Ipsum Dolor Sit Amet");
        jPanel6.add(jenisPengaduan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jPanel22.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 1310, 100));

        jPanel7.setBackground(new java.awt.Color(26, 26, 26));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        status3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        status3.setForeground(new java.awt.Color(255, 102, 0));
        status3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        status3.setText("Sedang Dalam Proses");
        jPanel7.add(status3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 30, 190, -1));

        judul3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        judul3.setForeground(new java.awt.Color(255, 255, 255));
        judul3.setText("Lorem Ipsum Dolor Sit Amet");
        jPanel7.add(judul3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jenisPengaduan3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jenisPengaduan3.setForeground(new java.awt.Color(153, 153, 153));
        jenisPengaduan3.setText("Lorem Ipsum Dolor Sit Amet");
        jPanel7.add(jenisPengaduan3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jPanel22.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 1310, 100));

        jPanel8.setBackground(new java.awt.Color(26, 26, 26));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        status4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        status4.setForeground(new java.awt.Color(255, 102, 0));
        status4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        status4.setText("Sedang Dalam Proses");
        jPanel8.add(status4, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 30, 190, -1));

        judul4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        judul4.setForeground(new java.awt.Color(255, 255, 255));
        judul4.setText("Lorem Ipsum Dolor Sit Amet");
        jPanel8.add(judul4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jenisPengaduan4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jenisPengaduan4.setForeground(new java.awt.Color(153, 153, 153));
        jenisPengaduan4.setText("Lorem Ipsum Dolor Sit Amet");
        jPanel8.add(jenisPengaduan4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jPanel22.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 1310, 100));

        jPanel9.setBackground(new java.awt.Color(26, 26, 26));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        status5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        status5.setForeground(new java.awt.Color(255, 102, 0));
        status5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        status5.setText("Sedang Dalam Proses");
        jPanel9.add(status5, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 30, 190, -1));

        judul5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        judul5.setForeground(new java.awt.Color(255, 255, 255));
        judul5.setText("Lorem Ipsum Dolor Sit Amet");
        jPanel9.add(judul5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jenisPengaduan5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jenisPengaduan5.setForeground(new java.awt.Color(153, 153, 153));
        jenisPengaduan5.setText("Lorem Ipsum Dolor Sit Amet");
        jPanel9.add(jenisPengaduan5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jPanel22.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 1310, 100));

        jPanel21.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 77, 1330, 680));

        head.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        head.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/head.png"))); // NOI18N
        head.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        head.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headMouseDragged(evt);
            }
        });
        head.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headMousePressed(evt);
            }
        });
        jPanel21.add(head, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 280, 27));

        jPanel1.setBackground(new java.awt.Color(25, 25, 25));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/BATAS.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 0, -1, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/BATAS.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, -1, 50));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/BATAS.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, -1, 50));

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/USER BLANK.png"))); // NOI18N
        jLabel9.setText(" GEOFANY GALINDRA");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 10, -1, -1));

        homeBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        homeBtn.setForeground(new java.awt.Color(255, 255, 255));
        homeBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/BERANDA BLANK.png"))); // NOI18N
        homeBtn.setText(" BERANDA");
        jPanel1.add(homeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        eventBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        eventBtn.setForeground(new java.awt.Color(255, 255, 255));
        eventBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eventBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/EVENT BLANK.png"))); // NOI18N
        eventBtn.setText(" EVENT");
        jPanel1.add(eventBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        pengaduanBtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        pengaduanBtn.setForeground(new java.awt.Color(118, 185, 0));
        pengaduanBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pengaduanBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/PENGADUAN FILL.png"))); // NOI18N
        pengaduanBtn.setText(" PENGADUAN");
        jPanel1.add(pengaduanBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        logoutBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        logoutBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/EXIT BLANK.png"))); // NOI18N
        jPanel1.add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, -1, -1));

        settingBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        settingBtn.setForeground(new java.awt.Color(255, 255, 255));
        settingBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        settingBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/SETTING BLANK.png"))); // NOI18N
        jPanel1.add(settingBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 10, -1, -1));

        jPanel21.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 1330, 50));

        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Exit.png"))); // NOI18N
        exitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnMouseClicked(evt);
            }
        });
        jPanel21.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 10, -1, -1));

        minimizeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Minimize.png"))); // NOI18N
        minimizeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimizeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeBtnMouseClicked(evt);
            }
        });
        jPanel21.add(minimizeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void klikEvent(MouseAdapter action){
        eventBtn.addMouseListener(action);
    }
    
    public void klikHome(MouseAdapter action) {
        homeBtn.addMouseListener(action);
    }
    
    public void klikLogout(MouseAdapter action){
        logoutBtn.addMouseListener(action);
    }
    
    public void klikSetting(MouseAdapter action) {
        settingBtn.addMouseListener(action);
    }
    
    public void klikPengaduanBaru(MouseAdapter action){
        pengaduanBaruBtn.addMouseListener(action);
    }
    
    public void klikHistoryPengaduan(MouseAdapter action){
        historyPengaduanBtn.addMouseListener(action);
    }
    
    public void klikDetailPengaduan(MouseAdapter action){
        judul1.addMouseListener(action);
        judul2.addMouseListener(action);
        judul3.addMouseListener(action);
        judul4.addMouseListener(action);
        judul5.addMouseListener(action);
    }
    
    public void klikEditPengaduan(MouseAdapter action){
        editPengaduan1Btn.addMouseListener(action);
        editPengaduan2Btn.addMouseListener(action);
   }
    
    public void klikHapusPengaduan(MouseAdapter action){
        hapusPengaduan1Btn.addMouseListener(action);
        hapusPengaduan2Btn.addMouseListener(action);
    }
    
    public void setPengaduan1(String judul, String jenis, String status){
        judul1.setText(judul);
        jenisPengaduan1.setText(jenis);
        status1.setText(status);
    }
    
    public void setPengaduan2(String judul, String jenis, String status){
        judul2.setText(judul);
        jenisPengaduan2.setText(jenis);
        status2.setText(status);
    }
    
    public void setPengaduan3(String judul, String jenis, String status){
        judul3.setText(judul);
        jenisPengaduan3.setText(jenis);
        status3.setText(status);
    }
    
    public void setPengaduan4(String judul, String jenis, String status){
        judul4.setText(judul);
        jenisPengaduan4.setText(jenis);
        status4.setText(status);
    }
    
    public void setPengaduan5(String judul, String jenis, String status){
        judul5.setText(judul);
        jenisPengaduan5.setText(jenis);
        status5.setText(status);
    }
    
    public int confirm(String isi){
        return JOptionPane.showConfirmDialog(this, isi, "Confirm", JOptionPane.YES_NO_OPTION , JOptionPane.QUESTION_MESSAGE);
    }
    
    public void message(String isi){
        JOptionPane.showMessageDialog(this, isi);
    }
    
    private void headMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headMouseDragged
        // TODO add your handling code here:
        int koordinatX = evt.getXOnScreen();
        int koordinatY = evt.getYOnScreen();
        this.setLocation(koordinatX-mouseX, koordinatY-mouseY);
    }//GEN-LAST:event_headMouseDragged

    private void headMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headMousePressed
        // TODO add your handling code here:
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_headMousePressed

    private void exitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseClicked
        // TODO add your handling code here:
        this.dispose();
        System.exit(1);
    }//GEN-LAST:event_exitBtnMouseClicked

    private void minimizeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMouseClicked
        this.setState(V_login.ICONIFIED);    // TODO add your handling code here:
    }//GEN-LAST:event_minimizeBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_prosesPengaduan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_prosesPengaduan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_prosesPengaduan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_prosesPengaduan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_prosesPengaduan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel editPengaduan1Btn;
    private javax.swing.JLabel editPengaduan2Btn;
    private javax.swing.JLabel eventBtn;
    private javax.swing.JLabel exitBtn;
    private javax.swing.JLabel hapusPengaduan1Btn;
    private javax.swing.JLabel hapusPengaduan2Btn;
    private javax.swing.JLabel head;
    private javax.swing.JLabel historyPengaduanBtn;
    private javax.swing.JLabel homeBtn;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jenisPengaduan1;
    private javax.swing.JLabel jenisPengaduan2;
    private javax.swing.JLabel jenisPengaduan3;
    private javax.swing.JLabel jenisPengaduan4;
    private javax.swing.JLabel jenisPengaduan5;
    private javax.swing.JLabel judul1;
    private javax.swing.JLabel judul2;
    private javax.swing.JLabel judul3;
    private javax.swing.JLabel judul4;
    private javax.swing.JLabel judul5;
    private javax.swing.JLabel logoutBtn;
    private javax.swing.JLabel minimizeBtn;
    private javax.swing.JLabel pengaduanBaruBtn;
    private javax.swing.JLabel pengaduanBtn;
    private javax.swing.JLabel prosesBtn;
    private javax.swing.JLabel settingBtn;
    private javax.swing.JLabel status1;
    private javax.swing.JLabel status2;
    private javax.swing.JLabel status3;
    private javax.swing.JLabel status4;
    private javax.swing.JLabel status5;
    // End of variables declaration//GEN-END:variables
}
